### ISSUE TITLE
推荐一个去广告的配置

### ISSUE THREAD

**Issue by ghost** [garypang13/luci-app-dnsfilter#4]
The Powerful Friendly Uptodate AD Blocking Hosts  最新强大而友善的去广告

https://github.com/neodevpro/neodevhost

**Comment by kiddin9** [comment]
看了下,法轮功媒体相关的网站都被屏蔽了，我可以不去看，但不能剥夺我看的权力, 不然就和GFW没啥区别了,

**Comment by kingtami** [comment]
> 看了下,法轮功媒体相关的网站都被屏蔽了，我可以不去看，但不能剥夺我看的权力, 不然就和GFW没啥区别了,

您真能装,哈哈哈.

**Comment by kiddin9** [comment]
> > 看了下,法轮功媒体相关的网站都被屏蔽了，我可以不去看，但不能剥夺我看的权力, 不然就和GFW没啥区别了,
> 
> 您真能装,哈哈哈.

怎么装了?好笑吗? 去广告插件那唯一功能就是去广告就应该是完全中立的,如果仅凭个人喜好就能随意屏蔽,那我还觉得共产党比法轮功恶劣一万倍呢, 除了某党国,法轮功在全世界都是合法的,你该想想为什么在党国,所有东西都和全世界都不一样,

**Comment by kingtami** [comment]
> > > 看了下,法轮功媒体相关的网站都被屏蔽了，我可以不去看，但不能剥夺我看的权力, 不然就和GFW没啥区别了,
> > 
> > 
> > 您真能装,哈哈哈.
> 
> 怎么装了?好笑吗? 去广告插件那唯一功能就是去广告就应该是完全中立的,如果仅凭个人喜好就能随意屏蔽,那我还觉得共产党比法轮功恶劣一万倍呢, 除了某党国,法轮功在全世界都是合法的,你该想想为什么在党国,所有东西都和全世界都不一样,

嗯,你不会自己把大妓院加到白名单吗?那些都是弱智看的东西.

**Comment by kiddin9** [comment]
> > > > 看了下,法轮功媒体相关的网站都被屏蔽了，我可以不去看，但不能剥夺我看的权力, 不然就和GFW没啥区别了,
> > > 
> > > 
> > > 您真能装,哈哈哈.
> > 
> > 
> > 怎么装了?好笑吗? 去广告插件那唯一功能就是去广告就应该是完全中立的,如果仅凭个人喜好就能随意屏蔽,那我还觉得共产党比法轮功恶劣一万倍呢, 除了某党国,法轮功在全世界都是合法的,你该想想为什么在党国,所有东西都和全世界都不一样,
> 
> 嗯,你不会自己把大妓院加到白名单吗?那些都是弱智看的东西.

和墙内脑子已经被塞满shit的人将道理真的是累,大家都是成年人有正常的思维和行为能力, 哪些内容是弱智需要别人来给你来做筛选和评判吗? 最后的结果就是十几亿人被圈养起来每天被喂shit.

**Comment by alegoho** [comment]
> 看了下,法轮功媒体相关的网站都被屏蔽了，我可以不去看，但不能剥夺我看的权力, 不然就和GFW没啥区别了,

大佬，有好用的规则吗？

**Comment by kingtami** [comment]
> > > > > 看了下,法轮功媒体相关的网站都被屏蔽了，我可以不去看，但不能剥夺我看的权力, 不然就和GFW没啥区别了,
> > > > 
> > > > 
> > > > 您真能装,哈哈哈.
> > > 
> > > 
> > > 怎么装了?好笑吗? 去广告插件那唯一功能就是去广告就应该是完全中立的,如果仅凭个人喜好就能随意屏蔽,那我还觉得共产党比法轮功恶劣一万倍呢, 除了某党国,法轮功在全世界都是合法的,你该想想为什么在党国,所有东西都和全世界都不一样,
> > 
> > 
> > 嗯,你不会自己把大妓院加到白名单吗?那些都是弱智看的东西.
> 
> 和墙内脑子已经被塞满shit的人将道理真的是累,大家都是成年人有正常的思维和行为能力, 哪些内容是弱智需要别人来给你来做筛选和评判吗? 最后的结果就是十几亿人被圈养起来每天被喂shit.

说那么多,你就是个轮子罢了,死轮子.
