### ISSUE TITLE
安装后在服务菜单里面不可见，卸载后换1.05正常

### ISSUE THREAD

**Issue by dalmie** [garypang13/luci-app-dnsfilter#6]
固件版本	OpenWrt R21.2.1 2021.02.24 compiled by tg:@zhe_teng / LuCI Master (git-21.035.34289-13f96d1)
内核版本	5.4.98-flippy-53+o

**Comment by kiddin9** [comment]
已修复,重新下载安装,

**Comment by dalmie** [comment]
可以了，感谢
